# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-06 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20190206_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
